FROM node:18 AS builder                                                            
WORKDIR /app
COPY . .
RUN npm install -g @angular/cli
RUN ng analytics off
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/www /usr/share/nginx/html
COPY ./config/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
